name: 'formatting'
description: 'CI formatting check'
inputs:
  path:
    description: 'Path to repository folder to run formatting check for. '
    required: false
    default: ./
  exclude-files:
    description: 'List of comma-separated files to exclude from the formatting check. Eg file1,file2'
    required: false
    default: ''
  exclude-dirs:
    description: 'List of comma-separated directories to exclude from the formatting check. Eg docs,build'
    required: false
    default: ''
  include-extensions:
    description: 'List of comma-separated extensions to add to the formatting check . Eg md,dox'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
      - env:
          stepName: Install Clang Format
        name: ${{ env.stepName }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo "::group::${{ env.stepName }}"
          sudo apt-get install clang-format fd-find
          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
          
          fdfind --version
          fdInstalled=$?

          clang-format --version
          clangFormatInstalled=$?

          set +e
          echo -e "GITHUB_ACTION_PATH= $GITHUB_ACTION_PATH"
          echo -e "ls GITHUB_ACTION_PATH = $(ls $GITHUB_ACTION_PATH)"
          echo -e "pwd= $(pwd)";
          echo "PATH=$PATH"
          set -e

          getFiles --help
          getFilesAdded=$?
          echo -e "getFilesAdded=$getFilesAdded"

          echo "::endgroup::"
          if [ $getFilesAdded -eq 1 ] || [ $clangFormatInstalled -eq 1] || [ $fdInstalled -eq 1 ]; then
            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
            exit 1
          else
            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
            exit 0
          fi

      - env:
          stepName: Validate Inputs
          # The bash escape character is \033
          # At time of writing, you can't add a global environment
          # to an action file so stuck with this. If this gets changed
          # Please move this
          bashPass:   \033[32;1mPASSED -
          bashInfo:   \033[33;1mINFO -
          bashFail:   \033[31;1mFAILED -
          bashEnd:    \033[0m
        name: ${{ env.stepName }}
        id: validate-inputs
        shell: bash
        run: |
          # ${{ env.stepName }}
          # Check exclude dirs for possible input issues
          if [[ "${{ inputs.exclude-dirs }}" = *"\n"* ]]; then
            echo -e "${{ env.bashFail }} YOU HAVE NEWLINE IN YOUR EXCLUDE-DIRS. ${{ env.bashEnd }}"
            exitStatus=1
          fi

      - env:
          stepName: Run Clang Format
        name: ${{ env.stepName }}
        if: ${{ steps.validate-inputs.outcome}} = "success"
        working-directory: ${{ inputs.path }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo -e "${{ env.bashInfo }} Using clang-format version "$(clang-format --version)" ${{ env.bashEnd }}"
          echo "::group::${{ env.stepName }}"

          # GitHub automatically use "set -e" which causes scripts to fail on the first exit code
          # This would mean the first time a file fails the check that we exit without formatting all files.
          set +e

          files=$(getFiles --exclude-files="${{inputs.exclude-files}}" --exclude-dir="${{inputs.exclude-dirs}}" )
          if [ ! $? -eq 0 ]; then
              echo -e "${{ env.bashFail }} Error calling getFiles() ${{ env.bashEnd }}"
              echo -e "$fileOut"
          fi

          # Loop over the files that matched the above conditions
          for file in ${files[@]}; do
            # Print them out for future debugging
            echo -e "${{ env.bashInfo }} Parsing File: "$file" ${{ env.bashEnd }}"

            # Pipe the output of the command to a variable
            # This way we can print the command only if it fails
            fileOut=$(clang-format -i --verbose --style=file $file)
            # If the previous command failed then print out an error message as well as the output
            if [ ! $? -eq 0 ]; then
              echo -e "${{ env.bashFail }} Error parsing "$file" ${{ env.bashEnd }}"
              echo -e "$fileOut"
            fi
          done

          echo "::endgroup::"
          # Run a git diff to print the differences if any exist, return an error code if there are any

          echo "::group::File Difference"
          git diff --exit-code
          echo "::endgroup::"
          exitCode=$?
          if [ $exitCode -eq 0 ]; then
            echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"
          else
            echo -e "${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
            echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
            echo -e "${{ env.bashFail }} ${{env.stepName }} ${{ env.bashEnd }}"
            # If there is an error, set this flag high again so the exit 1 fails the run instantly
            set -e
            exit 1
          fi

      - env:
          stepName: Check For Trailing Whitespace
        name: ${{ env.stepName }}
        shell: bash
        # Use this so that even if we fail formatting these checks run
        # Solves the issue of "Make commit to fix formatting, to then learn
        # You need to fix whitespace
        if: success() || failure() && ${{ steps.validate-inputs.outcome}} = "success"
        working-directory: ${{ inputs.path }}
        run: |
          # ${{ env.stepName }}
          echo "::group::${{ env.stepName }}"

          set +e
          files=$(getFiles --exclude-files="${{inputs.exclude-files}}" --exclude-dir="${{inputs.exclude-dirs}}" )

          for file in ${files[@]}; do
            grep -nIe "[[:blank:]]$" "$file" > $fileOut
            if [ $? -eq 0 ]; then
              echo "${{ env.bashFail }} "$fileOut" ${{ env.bashEnd }}"
              exitStatus=1;
            fi
          done

          echo "::endgroup::"
          if [ $exitStatus -eq 1 ]; then
            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
            set -e
            exit 1
          else
            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
            exit 0
          fi

      - env:
          stepName: Check for CRLF
        name: ${{ env.stepName }}
        if: success() || failure() && ${{ steps.validate-inputs.outcome}} = "success"
        working-directory: ${{ inputs.path }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          set +e

          files=$(getFiles --exclude-files="${{inputs.exclude-files}}" --exclude-dir="${{inputs.exclude-dirs}}" )
          for file in ${files[@]}; do
            grep -nl $'\r' "$file" > $fileOut
            if [ $? -eq 0 ]; then
              echo "${{ env.bashFail }} "$fileOut" ${{ env.bashEnd }}"
              exitStatus=1;
            fi
          done
          if [ $exitStatus -eq 1 ]; then
            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
            set -e
            exit 1
          else
            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
            exit 0
          fi
