name: 'spellings'
description: 'CI spellings check'
inputs:
  path:
    description: 'Path to repository folder to check spellings in.'
    required: false
    default: ./
runs:
  using: "composite"
  steps:
      - name: Install spell
        run: |
          sudo apt-get install spell
          sudo apt-get install util-linux
          sudo apt-get install npm
          npm install -g cspell
        shell: bash
      - name: Check spelling
        working-directory: ${{ inputs.path }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cspell --language-id C --unique --words-only "**/*.c" "**/*.h" | sort --ignore-case >> $GITHUB_ACTION_PATH/shared-dict.txt
          cd $GITHUB_ACTION_PATH/
          git add shared-dict.txt
          git commit -m "Updating shared-dict.txt"
          git push origin main
        shell: bash
